add basic compile/test like other redhat-appstudio projects
redhat-appstudio/sprayproxy pull request #22
Opened 2023-02-07 19:33 UTC by gabemontero

generally, redhat-appstudio projects have done basic `make` type invocations via github actions, and triggered e2e tests via openshift/release prow integrations

2023-02-07 19:39 UTC, gabemontero commented
but I'll wait for talking to @adambkaplan before we enable actions for this repo in the same fashion that we have enabled the other redhat-appstudio repos

2023-02-08 18:22 UTC, adambkaplan commented
/ok-to-test

2023-02-08 18:24 UTC, adambkaplan requested changes

2023-02-08 18:24 UTC, adambkaplan commented on .tekton/unit-test.yaml
> +            value: $(params.revision)
ClusterTasks are deprecated (or will be soon). Reference the clone task in the hacbs bundle instead.

2023-02-08 18:39 UTC, gabemontero commented on .tekton/unit-test.yaml
> +            value: $(params.revision)
yeah after I got blocked testing after too many retries ;-)  I pivoted over to testing locally first @adambkaplan (and hence why I grabbed the cluster task git-clone like what is specified in pipeline-service CI vs. moving do a bundle ref)

I have a form of it working now, but am still iterating, but FYI there are several changes besides what you just asked for that are needed

I'm marking PR WIP for now.  Will remove WIP prefix and tag you when it is ready.

2023-02-08 19:27 UTC, gabemontero commented on .tekton/unit-test.yaml
> +            value: $(params.revision)
ok bundle ref to git-clone task from build-definitions added

2023-02-08 19:28 UTC, gabemontero commented
the unit test is running / passing @adambkaplan 

IMO what I had to do here speaks to some of the eat our own dogfood gaps we talked about in the retrospective today

2023-02-15 19:33 UTC, adambkaplan approved these changes
/lgtm

2023-02-15 19:33 UTC, merged